-- IMPLEMENT DATABASE
CREATE DATABASE IF NOT EXISTS OI;
CREATE DATABASE OI;
USE OI;

-- TASKS TABLE IMPLEMENTATION
DROP TABLE IF EXISTS task;
CREATE TABLE task (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100),
    PRIMARY KEY (id)
);

-- ADD TASK
DROP PROCEDURE IF EXISTS add_task;
DELIMITER //
CREATE PROCEDURE add_task(IN task_name VARCHAR(100))
BEGIN
    INSERT INTO task (name)
	VALUES (task_name);
END //
DELIMITER ;

-- GET TASKS
DROP PROCEDURE IF EXISTS get_task;
DELIMITER //
CREATE PROCEDURE get_task()
BEGIN
	SELECT * FROM task;
END //
DELIMITER ;

-- DELETE FIRST TASK
DROP PROCEDURE IF EXISTS delete_first_task;
DELIMITER //
CREATE PROCEDURE delete_first_task()
BEGIN
	DECLARE min_id INT;
    SET min_id = (SELECT MIN(id) FROM task);
	DELETE FROM task WHERE id = min_id;
END //
DELIMITER ;

